### PR TITLE
Add an option to follow symbolic links

### PR DESCRIPTION
**Pull request by ludwiktrammer**
This will help to resolve this issue in `node-sass`: https://github.com/sass/node-sass/issues/1952

### CODE REVIEW

**Comment by xzyfer** [comment]
Thank @ludwiktrammer. This seems reasonable. I'll prep a release tomorrow.

**Comment by ludwiktrammer** [comment]
Thank you!

**Comment by ludwiktrammer** [comment]
Hi. Any updates on merging this?

**Comment by xzyfer** [comment]
Sorry I haven't had the time to come back to this. Looks like you're latest commit mistakenly introduced a .DS_Store file. Please remove that I'll try to get this shipped before my holiday.

**Comment by ludwiktrammer** [comment]
I removed the `.DS_Store` file. Sorry about that!

**Comment by xzyfer** [comment]
Thanks

**Pull request merged**
