### PR TITLE
Added support for sass "indented" files

### PR DESCRIPTION
**Pull request by vegetableman**
Reference #22

### CODE REVIEW

**Comment by vegetableman** [comment]
No love for sass?

**Comment by xzyfer** [comment]
Thanks heaps for this, I haven't had the time recently.

**Comment by vegetableman** [comment]
Thanks a ton @xzyfer . And there I was thinking, whether old sass is being deprecated.

**Comment by xzyfer** [comment]
i'm still working on that :stuck_out_tongue_closed_eyes:

**Pull request merged**
